function k(b,a,c,d){b.v.Db(b.jb,a,c,d,void 0)}function l(b,a,c,d){b.v.ma?k(b,a,c,d):b.v.re()._OnMessageFromDOM({type:"event",component:b.jb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.v.C(b.jb,a,c)}function t(b,a){for(const [c,d]of a)p(b,c,d)}function u(b){b.Ob||(b.v.bd(b.Ld),b.Ob=!0)}window.ab=class{constructor(b,a){this.v=b;this.jb=a;this.Ob=!1;this.Ld=()=>this.Ka()}Uc(){}Ka(){}};
window.af=class{constructor(){this.Rc=-1}j(){-1!==this.Rc&&(self.clearTimeout(this.Rc),this.Rc=-1)}};"use strict";function aa(b,a){p(b,"get-element",c=>{const d=v(b,c.elementId);return a(d,c)})}function v(b,a){b=b.Mb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.od}
window.$e=class extends self.ab{constructor(b,a){super(b,a);this.Mb=new Map;this.zc=!0;t(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=v(this,c);this.zc&&d.parentElement.removeChild(d);this.Mb.delete(c)}],["set-visible",c=>{if(this.zc){var d=this.Mb.get(c.elementId),e=d.od;d.ud?e.style.display=c.isVisible?"":"none":d.He=!!c.isVisible}}],["update-position",c=>{if(this.zc){var d=this.Mb.get(c.elementId),e=d.od;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.ud||(d.ud=!0,d.He&&(e.style.display=""))}}],["update-state",c=>{v(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=v(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",
c=>{v(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent);let ca=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Qe?new Promise(c=>{const d="c3_resolve_"+ca;++ca;self[d]=c;a.textContent=b.Ue+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let da=!1,ea=!1;function fa(){if(!da){try{new Worker("blob://",{get type(){ea=!0}})}catch(b){}da=!0}return ea}let z=new Audio;
const ha={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ia(b){b=await ja(b);return(new TextDecoder("utf-8")).decode(b)}
function ja(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ka=0;const na=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");na.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);let pa=!1;
window.gb=class b{constructor(a){this.ma=a.We;this.va=null;this.ba="";this.Xa=a.Te;this.zb={};this.Qa=this.ta=null;this.Lb=[];this.H=this.wa=null;this.Hc=!1;this.rd=0;this.ob=null;this.Wa=-1;this.Le=()=>this.ye();this.Va=[];this.B=a.Md;this.Pb="file"===location.protocol.substr(0,4);!this.ma||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&fa()||(this.ma=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ma=!1;if("cordova"===this.B&&this.ma)if(w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ma=!1)}else this.ma=!1;this.Sb=this.qa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.ue(c));this.C("runtime","create-job-worker",()=>this.ve());"cordova"===this.B?document.addEventListener("deviceready",()=>this.ed(a)):this.ed(a)}j(){this.qc();
this.va&&(this.va=this.va.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}ge(){return ba&&"cordova"===this.B}mc(){const a=navigator.userAgent;return ba&&oa.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ee(){return w}Zc(){return w&&oa.has(this.B)}async ed(a){"macos-wkwebview"===this.B&&this.De();if("playable-ad"===this.B){this.qa=self.c3_base64files;this.Sb={};await this.ne();
for(let d=0,e=a.Za.length;d<e;++d){var c=a.Za[d];this.Sb.hasOwnProperty(c)?a.Za[d]={Qe:!0,Ue:this.Sb[c]}:this.qa.hasOwnProperty(c)&&(a.Za[d]=URL.createObjectURL(this.qa[c]))}a.ec=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.bd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Se?this.ba=a.Se:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.Ye&&(this.zb=a.Ye);
c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.xe(d));this.ob=new self.he(this);await qa(this.ob);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ma?await this.te(a,c.port2):
await this.se(a,c.port2)}sc(a){a=this.zb.hasOwnProperty(a)?this.zb[a]:a.endsWith("/workermain.js")&&this.zb.hasOwnProperty("workermain.js")?this.zb["workermain.js"]:"playable-ad"===this.B&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async hc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Pb)return a=await this.Bb(d.Pe?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}dd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ha(),g=window.devicePixelRatio,h=b.eb(),m=a.ef,q=window.cr_previewImageBlobs||this.qa,n=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.cf||
"";a=a.Md;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.ob;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:n,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.df,jobScheduler:{inputPort:B.Gc,outputPort:B.Nc,maxNumWorkers:B.Ie},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Xa+"opus.wasm.wasm",isFileProtocol:this.Pb,isiOSCordova:this.ge(),isiOSWebView:this.mc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async te(a,c){const d=this.sc(a.Xe);"preview"===this.B?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=n=>{this.ta.removeEventListener("message",q);n.data&&"ok"===n.data.type?h():m()};this.ta.addEventListener("message",q);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ta=await this.hc(d,this.ba,{type:"module",name:"Runtime",Pe:!0});this.H=document.createElement("canvas");this.H.style.display="none";const e=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ec||[],g=a.Za;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.B)for(let h=0,m=a.dc.length;h<m;++h){const q=
a.dc[h],n=q[0];if(n===a.Sc||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))q[1]=await this.La(n)}this.ta.postMessage(Object.assign(this.dd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.dc,mainProjectScript:a.Sc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ra(this.ob)]);this.Lb=F.map(h=>new h(this));this.cd();sa(this.wa);self.c3_callFunction=(h,m)=>{var q=this.wa;return q.v.ad(q.jb,"js-invoke-function",
{name:h,params:m},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Db("runtime","go-to-last-error-script"))}async se(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Lb=F.map(g=>new g(this));this.cd();var d=a.Za.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.ec)&&d.unshift(...a.ec);d=await Promise.all(d.map(g=>
this.La(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;const e=a.Sc,f=a.dc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await y(h),"preview"!==this.B||d[g]||this.gd(g,"main script did not run to completion")}catch(m){this.gd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await y(h);"preview"===this.B&&"object"!==typeof self.Ze.bf?(this.Hb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.dd(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:na}),sa(this.wa),this.fd(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}gd(a,c){this.Hb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}fd(){this.Hb()}Hb(){const a=
window.Ne;a&&(a.parentElement.removeChild(a),window.Ne=null)}async ve(){const a=await ta(this.ob);return{outputPort:a,transferables:[a]}}re(){if(this.ma)throw Error("not available in worker mode");return this.Qa}Db(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}ad(a,c,d,e,f){const g=ka++,h=new Promise((m,q)=>{H.set(g,{resolve:m,reject:q})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.we(a);if("result"===c)this.ze(a);else if("runtime-ready"===c)this.Ae();else if("alert-error"===c)this.Hb(),alert(a.message);else if("creating-runtime"===c)this.fd();else throw Error(`unknown message '${c}'`);}we(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Gb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Gb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Gb(f,!1,""+h)}):this.Gb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Gb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}ze(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}C(a,
c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ab(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}cd(){for(const a of this.Lb)if("runtime"===a.jb){this.wa=a;return}throw Error("cannot find runtime DOM handler");}xe(a){this.Db("debugger","message",a)}Ae(){for(const a of this.Lb)a.Uc()}static eb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
pa)}static hd(a){pa=!!a}bd(a){this.Va.push(a);this.xc()}Ce(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");this.Va.splice(a,1);this.Va.length||this.qc()}xc(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Le))}qc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}ye(){this.Wa=-1;for(const a of this.Va)a();this.xc()}Ba(a){this.wa.Ba(a)}Ja(a){this.wa.Ja(a)}wc(){this.wa.wc()}Fb(a){this.wa.Fb(a)}fe(){return!!ha["audio/webm; codecs=opus"]}async Ee(a){a=await this.ad("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}je(a){this.Hc=!0;this.rd=a}de(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}$c(a){return!this.de(a)}async La(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Pb&&this.$c(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Bb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ue(a){const c=a.filename;switch(a.as){case "text":return await this.ce(c);
case "buffer":return await this.Bb(c);default:throw Error("unsupported type");}}Xc(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ce(a){a=await this.Xc(a);return await ia(a)}rc(){if(C.length&&!(8<=E)){E++;var a=C.shift();this.oe(a.filename,a.Ve,a.Oe)}}Bb(a){return new Promise((c,d)=>{C.push({filename:a,Ve:e=>{E--;this.rc();c(e)},Oe:e=>{E--;this.rc();d(e)}});this.rc()})}async oe(a,c,d){try{const e=
await this.Xc(a),f=await ja(e);c(f)}catch(e){d(e)}}De(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ne(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.me(c,d));await Promise.all(a)}async me(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),
this.Sb[a]=c.str;else{let d=await this.qe(c);d||(d=this.pe(c));this.qa[a]=d}}async qe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}pe(a){a=this.Be(a);return this.le(a.data,a.Re)}Be(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+
1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Re:a,data:d}}le(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const I=self.gb;
function ua(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},xa={dispatchRuntimeEvent:!0};
function ya(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function za(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await za(b)}finally{URL.revokeObjectURL(b)}}
function Aa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ba(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Aa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ca(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ba(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ga=!1;document.addEventListener("pause",()=>Ga=!0);document.addEventListener("resume",()=>Ga=!1);function sa(b){b.qd=!0;b.Kc=b.v.oa();b.pb=b.v.ha()}async function Ha(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ia(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ja(b){return await self.C3_GetSvgImageSize(b.blob)}function Ka(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function La(b){self.setTimeout(()=>{b.pd=!0},1E3);"cordova"===b.v.B?(document.addEventListener("pause",()=>Ma(b,!0)),document.addEventListener("resume",()=>Ma(b,!1))):document.addEventListener("visibilitychange",()=>Ma(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ga)}}
function Na(b){b.kd||(b.kd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Oa(b){b.jd||(b.jd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Pa(b){await ya(b.url)}
function Qa(b,a){b.sd=a.message;-1===b.Cc&&(b.Cc=setTimeout(()=>{b.Cc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.sd)},250))}function M(b){if(!b.Z){var a=I.eb();a&&"any"!==b.Pc&&Ra(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ha()})}}function Sa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.eb(),innerWidth:b.oa(),innerHeight:b.ha()})}
function Ma(b,a){a?b.v.qc():b.v.xc();k(b,"visibilitychange",{hidden:a})}function Ta(b,a,c){"Backspace"===c.key&&L(c);if(!b.Z){var d=va.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}
function Ua(b,a,c,d){b.Z||ua(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Va(b){window!==window.top&&window.focus();Wa(b.target)&&document.activeElement&&!Wa(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.Z){var d=0;"mouse"===c.pointerType&&(d=b.ub);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Ua(b,d,c,wa),b.ub=c.buttons)}}
function Xa(b,a,c){if(!b.Z&&!ua(c)){var d=b.ub;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.ub=c.buttons;Ua(b,c.type,c,wa)}}
function O(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.ca,pageX:f.pageX,pageY:f.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function Ya(b,a,c){document.body.style.transform="";b.ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.ca=a))}}function Za(b,a,c,d){const e=b.oa(),f=b.ha();b.Ya=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.eb()}):10>d&&bb(b,e,f,d+1)}
function bb(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>Za(b,a,c,d),48)}
function Ra(b){b=b.Pc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Wa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.Ab(class extends self.ab{constructor(b){super(b,"runtime");this.yd=!0;this.qd=!1;this.Ya=-1;this.Pc="any";this.jd=this.kd=!1;this.ac=document.createElement("div");this.ac.className="c3-screen-reader-text";this.ac.setAttribute("aria-live","polite");document.body.appendChild(this.ac);this.Ea=null;this.Z=!1;this.sd="";this.Cc=-1;this.pd=!1;this.Kc=b.oa();this.pb=b.ha();this.ca=this.yb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Hc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.yd&&(e.style.display="",this.yd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ha(d));b.C("runtime","raster-svg-image",d=>Ia(d));b.C("runtime","get-svg-image-size",
d=>Ja(d));b.C("runtime","set-target-orientation",d=>{this.Pc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ka(d));b.C("runtime","go-to-script",d=>Ka(d));b.C("runtime","before-start-ticking",()=>La(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ea&&(this.Ea.style.display="none")});b.C("runtime","enable-device-orientation",()=>Na(this));b.C("runtime","enable-device-motion",()=>Oa(this));b.C("runtime","add-stylesheet",d=>Pa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ac.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.H.style.display="";this.v.je(d.duration)});b.C("runtime","export-to-video-progress",d=>Qa(this,d));b.C("runtime","exported-to-video",d=>{window.Me({type:"exported-video",
blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Me({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ca(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",L);window.addEventListener("touchstart",
L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.ub=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.qd){var d=this.oa();var e=this.ha();if(this.v.Zc()){if(this.pd){if(this.Kc===d&&
e<this.pb){this.yb=this.pb-e;Ya(this,this.pb,this.yb);d=void 0;break a}0<this.yb&&(this.yb=0,Ya(this,e,this.yb))}this.Kc=d;this.pb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.eb()});this.v.mc()&&(-1!==this.Ya&&clearTimeout(this.Ya),Za(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",()=>
M(this));window.addEventListener("fullscreenerror",d=>Sa(this,d));window.addEventListener("webkitfullscreenerror",d=>Sa(this,d));window.addEventListener("mozfullscreenerror",d=>Sa(this,d));if(b.mc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ca(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(I.hd(!0),M(this)):"exited-fullscreen"===d?(I.hd(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Ra=new Set;this.Ub=new WeakSet;this.ua=!1}Uc(){window.addEventListener("focus",()=>{k(this,"window-focus",null,xa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}k(this,"window-blur",{parentHasFocus:a},xa);this.ub=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||Ca(a))&&k(this,"keyboard-blur",null,xa)});window.addEventListener("keydown",a=>Ta(this,"keydown",a));window.addEventListener("keyup",a=>Ta(this,"keyup",a));window.addEventListener("dblclick",a=>Ua(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.ca,pageX:a.pageX,pageY:a.pageY+this.ca,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Va(a);N(this,"pointerdown",a)}),this.v.ma&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Va(a);Xa(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Xa(this,"pointermove",a)),window.addEventListener("mouseup",a=>Xa(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Va(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=
()=>this.wc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.ee()&&!this.v.Zc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ya(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ha(){return this.v.ha()}wc(){var b=
[...this.Ra];this.Ra.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Ub.has(a)||this.Ra.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");this.Ub.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.Ub.has(b)||this.Ra.add(b)})}Ja(b){this.Ra.delete(b);this.Ub.add(b)}Fb(b){this.ua=!!b}});"use strict";
async function qa(b){if(b.Fe)throw Error("already initialised");b.Fe=!0;var a=b.xa.sc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"dispatchworker.js");b.Bc=await b.xa.hc(a,b.ib,{name:"DispatchWorker"});a=new MessageChannel;b.Gc=a.port1;b.Bc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Nc=await ta(b)}function ra(b){return[b.Gc,b.Nc]}
async function ta(b){const a=b.zd.length;var c=b.xa.sc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"jobworker.js");c=await b.xa.hc(c,b.ib,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Bc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.zd.push(c);return e.port1}
self.he=class{constructor(b){this.xa=b;this.ib=b.ba;this.ib="preview"===b.B?this.ib+"workers/":this.ib+b.Xa;this.Ie=Math.min(navigator.hardwareConcurrency||2,16);this.Bc=null;this.zd=[];this.Nc=this.Gc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.gb({We:!0,Xe:"workermain.js",Za:["scripts/c3runtime.js"],dc:[],Sc:"",Te:"scripts/",ec:[],Md:"html5"}));"use strict";const cb=180/Math.PI;
async function db(b,a){if(a.isiOSCordova||a.isSafari)b.Xb=!0;b.Qc=a.timeScaleMode;b.Ed=["equalpower","HRTF","soundfield"][a.panningModel];b.nd=["linear","inverse","exponential"][a.distanceModel];b.Fd=a.refDistance;b.Dd=a.maxDistance;b.Hd=a.rolloffFactor;if(b.v.Hc)b.Xb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.rd)});else{var c={latencyHint:a.latencyHint};b.Kd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");eb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&eb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.da);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function fb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,n=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Ad=g;hb(b,g);try{b.$=await ib(b,c,d,e,g,f);if(n){Q(b.$,!0);var r=b.$,B=n.innerAngle,la=n.outerAngle,ma=n.outerGain;if(r.nb){jb(r,n.x,n.y,n.z,n.angle);var D=self.$a.ke;r.ra[0]!==D(B)&&(r.ra[0]=
D(B),r.F.coneInnerAngle=D(B));r.ra[1]!==D(la)&&(r.ra[1]=D(la),r.F.coneOuterAngle=D(la));r.ra[2]!==ma&&(r.ra[2]=ma,r.F.coneOuterGain=ma)}n.hasOwnProperty("uid")&&(b.$.pa=n.uid)}else"number"===typeof A&&0!==A?(R(b.$,!0),kb(b.$,A)):(Q(b.$,!1),R(b.$,!1));b.$.Play(h,m,q,x)}catch(vb){console.error("[Construct] Audio: error starting playback: ",vb);return}finally{c=b.wb.get(g);if(!c)throw Error("expected pending tag");c.Tc--;0===c.Tc&&(c.resolve(),b.wb.delete(g))}u(b)}
async function lb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await mb(b,c);for(const n of S(b,c)){c=n;var f=d,g=e,h=a;if(!c.Pa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.s.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ha=f;c.Oa=g;c.Jd=h}}T(b)}async function nb(b,a){const c=a.tag;a=a.rate;await mb(b,c);for(const d of S(b,c))b=d,b.la!==a&&(b.la=a,b.Ca())}
async function ob(b,a){const c=a.tag;a=a.pos;await mb(b,c);for(const d of S(b,c))d.nc(a)}async function pb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ib(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function qb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function rb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Sd(b,...e);else if("delay"===c)e=new self.Qd(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Pd(b,c.ia,...e);var f=a.bufferType;c.ld=a.bufferOriginalUrl;c.md=f}else if("flanger"===c)e=new self.Td(b,...e);else if("phaser"===c)e=new self.Vd(b,...e);else if("gain"===c)e=
new self.Ud(b,...e);else if("stereopan"===c)e=new self.Xd(b,...e);else if("tremolo"===c)e=new self.Yd(b,...e);else if("ringmod"===c)e=new self.Wd(b,...e);else if("distortion"===c)e=new self.Rd(b,...e);else if("compressor"===c)e=new self.Od(b,...e);else if("analyser"===c)e=new self.Nd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ka.get(d);e||(e=[],b.ka.set(d,e));a.xd=e.length;a.fa=d;e.push(a);sb(b,d);tb(b)}
async function ub(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.J)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.J=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.bc=a.timeScale;b.Dc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.da[e]=d[e];b.g.listener.setOrientation(...b.da)}b.ua=a.isSilent;b.v.Fb(b.ua);b.Tb=a.masterVolume;b.Na.gain.value=
b.Tb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>rb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>wb(b,f,c)));T(b)}
async function xb(b,a){try{const c=b.g.suspend(a.time);b.wd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Db("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>yb(d)),b.wd=!0);await c}catch(c){yb(c)}}
function eb(b){b.Nb||(b.Fc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Nb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.cb()===c)return await zb(g),g;if(f)return null;if(e&&(b.Xb||b.vd)){f=0;for(let h=0,m=b.ja.length;h<m;++h)g=b.ja[h],b.ja[f]=g,g.za()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.Kd;e&&f&&(b.vd=!0);c=!e||b.Xb||f?new self.ae(b,a,c,d,e,f):new self.Zd(b,a,c,d,e);b.ja.push(c);await zb(c);b.Cd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Cd.add(a));return c}
function Ab(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.na()}function sb(b,a){let c=b.na();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of S(b,a))d=c,e=f.ea||f.F||f.G,e.disconnect(),e.connect(d);b.Fa&&b.Lc===a&&(b.Fa.disconnect(),b.Fa.connect(c))}
function*S(b,a){if(a)for(const c of b.J)b=c.fa,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Bb(b,a,c){return c?b.v.Ee(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Cb(b,a){let c=0;for(let d=0,e=b.J.length;d<e;++d){const f=b.J[d];b.J[c]=f;f.O===a?f.j():++c}b.J.length=c}
async function ib(b,a,c,d,e,f){for(const g of b.J)if(g.cb()===c&&(g.fc()||f))return g.fa=e,g;a=await P(b,a,c,d,f);e="html5"===a.yc?new self.$d(a.s,a,e):new self.be(a.s,a,e);b.J.push(e);return e}function hb(b,a){let c=b.wb.get(a);if(!c){let d=null;c={Tc:0,promise:new Promise(e=>d=e),resolve:d};b.wb.set(a,c)}c.Tc++}function mb(b,a){a||(a=b.Ad);return(b=b.wb.get(a))?b.promise:Promise.resolve()}function T(b){if(0<b.Ma.size)u(b);else for(const a of b.J)if(!a.I&&!a.U()){u(b);break}}
function Db(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function tb(b){b.Ic||(b.Ic=!0,Promise.resolve().then(()=>Eb(b)))}function Eb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.bb());k(b,"fxstate",{fxstate:a});b.Ic=!1}
async function wb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,n=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ib(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),kb(b,d));c.Play(m,q,n,0);a.isPlaying||c.fb();c.uc(a)}}}function yb(b){console.error("[Audio] Offline rendering error: ",b)}
self.$a=class extends self.ab{constructor(b){super(b,"audio");this.Na=this.g=null;this.Nb=this.Fc=!1;this.ya=()=>{if(!this.Fc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Nb&&(this.Fc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Nb=!1)}};this.ja=[];this.J=[];this.$=null;this.Ad="";this.Cd=new Set;this.Bd=-1;this.wb=new Map;this.Tb=1;this.ua=!1;this.Qc=0;this.bc=1;this.Dc=0;this.Ed="HRTF";this.nd="inverse";this.Fd=600;this.Dd=1E4;this.Hd=1;this.aa=[0,0,0];this.da=[0,0,-1,0,1,0];this.vd=this.Xb=!1;this.Kd=this.v.fe();this.ka=new Map;this.Ma=new Set;this.wd=this.Ic=!1;this.Lc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Fa&&this.Fa.disconnect();this.Lc=c.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);
this.Fa.connect(Ab(this,this.Lc))};this.Kb=null;self.C3Audio_GetOutputStream=()=>{this.Kb||(this.Kb=this.g.createMediaStreamDestination(),this.Na.connect(this.Kb));return this.Kb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>db(this,a)],["play",a=>fb(this,a)],["stop",a=>{a=a.tag;for(const c of S(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.J)a.Aa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of S(this,c))a?d.fb():d.Eb();T(this)}],["set-volume",a=>
{const c=a.tag;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>lb(this,a)],["set-master-volume",a=>{this.Tb=a.vol;this.Na.gain.value=this.Tb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of S(this,c))Fb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.v.Fb(this.ua);for(const c of this.J)c.Ib()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of S(this,c))d.oc(a)}],["set-playback-rate",a=>nb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of S(this,
c))R(d,!0),kb(d,a)}],["seek",a=>ob(this,a)],["preload",a=>pb(this,a)],["unload",a=>qb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.J)c.pc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>rb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ka.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),tb(this))}],["remove-effects",a=>
{a=a.tag.toLowerCase();const c=this.ka.get(a);if(c&&c.length){for(const d of c)d.j();this.ka.delete(a);sb(this,a)}}],["tick",a=>{this.bc=a.timeScale;this.Dc=a.gameTime;this.Bd=a.tickCount;if(0!==this.Qc)for(var c of this.J)c.Ca();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.da[0]!==c[0]||this.da[1]!==c[1]||this.da[2]!==c[2]||this.da[3]!==
c[3]||this.da[4]!==c[4]||this.da[5]!==c[5])){for(let d=0;6>d;++d)this.da[d]=c[d];this.g.listener.setOrientation(...this.da)}for(const d of a.instPans){a=d.uid;for(const e of this.J)e.pa===a&&jb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>ub(this,a)],["offline-render-audio",a=>xb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Na}Cb(){return this.ua}Ba(b){this.v.Ba(b)}Ja(b){this.v.Ja(b)}Ka(){for(var b of this.Ma)b.Ka();b=this.g.currentTime;for(var a of this.J)a.Ka(b);
a=this.J.filter(c=>!c.I&&!c.U()).map(c=>c.bb());k(this,"state",{tickCount:this.Bd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.fa,index:c.xd,peak:c.Ua,rms:c.Gd,binCount:c.l.frequencyBinCount,freqBins:c.td}))});0===a.length&&0===this.Ma.size&&this.Ob&&(this.v.Ce(this.Ld),this.Ob=!1)}static ke(b){return b*cb}static Yc(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ie(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.gb.Ab(self.$a);
"use strict";function zb(b){b.Rb||(b.Rb=b.tc());return b.Rb}self.Vc=class{constructor(b,a,c,d,e){this.s=b;this.Ke=a;this.Ga=c;this.R=d;this.Ge=e;this.yc="";this.Rb=null}j(){this.Rb=this.s=null}tc(){}V(){return this.s.V()}jc(){return this.Ke}cb(){return this.Ga}ic(){return this.R}za(){return this.Ge}ga(){}};"use strict";
self.Zd=class extends self.Vc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.yc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.qb=this.rb=null;this.M.addEventListener("canplaythrough",()=>!0);this.vb=this.V().createGain();this.tb=null;this.M.addEventListener("canplay",()=>{this.rb&&(this.rb(),this.qb=this.rb=null);!this.tb&&this.M&&(this.tb=this.V().createMediaElementSource(this.M),this.tb.connect(this.vb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ga}' error: `,f);this.qb&&(this.qb(f),this.qb=this.rb=null)})}j(){Cb(this.s,this);this.vb.disconnect();this.vb=null;this.tb.disconnect();this.tb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}tc(){return new Promise((b,a)=>{this.rb=b;this.qb=a;this.M.src=this.Ga})}T(){return this.M}ga(){return this.M.duration}};"use strict";
async function Gb(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.B&&a.$c(b.Ga)&&a.Pb)b.Da=await a.Bb(b.Ga);else{a=await fetch(b.Ga);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Hb(b){if(b.ia)return b.ia;b.ia=await Bb(b.s,b.Da,b.Je);b.Da=null}
self.ae=class extends self.Vc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.yc="webaudio";this.ia=this.Da=null;this.Je=!!f}j(){Cb(this.s,this);this.ia=this.Da=null;super.j()}async tc(){try{await Gb(this),await Hb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ga}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Ib=0;
function Q(b,a){a=!!a;b.nb!==a&&(b.nb=a,b.nb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Ed,b.F.distanceModel=b.s.nd,b.F.refDistance=b.s.Fd,b.F.maxDistance=b.s.Dd,b.F.rolloffFactor=b.s.Hd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Qb!==a&&(b.Qb=a,b.Qb?(Q(b,!1),b.ea=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.na())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.na())))}function kb(b,a){b.Qb&&b.Oc!==a&&(b.ea.pan.value=a,b.Oc=a)}function U(b,a){b.Ha=a;b.G.gain.cancelScheduledValues(0);b.Oa=-1;b.G.gain.value=b.kc()}function Fb(b,a){a=!!a;b.Pa!==a&&(b.Pa=a,b.Ib())}
function jb(b,a,c,d,e){if(b.nb){var f=b.Ta,g=b.Sa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Jc?b.s.Dc:performance.now()/1E3}
self.Wc=class{constructor(b,a,c){this.s=b;this.O=a;this.fa=c;this.Jb=Ib++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.nb=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.ra=[0,0,0];this.ea=null;this.Qb=!1;this.Oc=0;this.I=!0;this.X=this.sa=this.K=!1;this.Ha=1;this.Pa=!1;this.la=1;b=this.s.Qc;this.Jc=1===b&&!this.za()||2===b;this.Oa=this.pa=-1;this.Jd=!1}j(){this.O=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}na(){return Ab(this.s,this.fa)}jc(){return this.O.jc()}cb(){return this.O.cb()}ic(){return this.O.ic()}za(){return this.O.za()}U(){}fc(){}IsPlaying(){return!this.I&&!this.K&&!this.U()}Ia(){}ga(){return this.O.ga()}Play(){}Aa(){}fb(){}Eb(){}Ka(b){-1!==this.Oa&&b>=this.Oa&&(this.Oa=-1,this.Jd&&this.Aa(),Db(this.s,"fade-ended",this.fa,this.Jb))}kc(){const b=this.Ha;return isFinite(b)?b:0}Cb(){return this.s.Cb()}Ib(){}oc(){}Ca(){}nc(){}pc(){}lc(){}bb(){var b=this.Jb,
a=this.fa,c=this.ga(),d=-1===this.Oa?this.Ha:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.jc(),bufferUrl:"",bufferType:this.ic(),isMusic:this.za(),isLooping:this.X,isMuted:this.Pa,resumePosition:this.lc(),pan:f,stereoPan:this.ea?this.Oc:
null}}uc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ca());Fb(this,b.isMuted)}};"use strict";
self.$d=class extends self.Wc{constructor(b,a,c){super(b,a,c);this.O.vb.connect(this.G);this.O.onended=()=>this.vc()}j(){this.Aa();this.O.vb.disconnect();super.j()}T(){return this.O.T()}vc(){this.I=!0;this.pa=-1;Db(this.s,"ended",this.fa,this.Jb)}U(){return this.T().ended}fc(){return this.I?!0:this.U()}Ia(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.cb()}' to position '${c}': `,e)}this.s.Ba(d);this.K=this.I=!1;this.X=b;this.la=1}Aa(){const b=this.T();b.paused||b.pause();this.s.Ja(b);this.I=!0;this.K=!1;this.pa=-1}fb(){if(!(this.K||this.I||this.U())){var b=this.T();b.paused||b.pause();this.s.Ja(b);this.K=!0}}Eb(){!this.K||this.I||this.U()||(this.s.Ba(this.T()),this.K=!1)}Ib(){this.T().muted=this.Pa||this.Cb()}oc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Ca(){let b=this.la;this.Jc&&(b*=this.s.bc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}nc(b){if(!this.I&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}lc(){return this.Ia()}pc(b){b?this.IsPlaying()?(this.T().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ba(this.T()),this.sa=!1)}};"use strict";function W(b){b.o&&b.o.disconnect();b.o=null;b.hb=null}
self.be=class extends self.Wc{constructor(b,a,c){super(b,a,c);this.o=null;this.Vb=d=>this.vc(d);this.Ec=!0;this.hb=null;this.P=this.Wb=this.Yb=0;this.Mc=1}j(){this.Aa();W(this);this.Vb=null;super.j()}vc(b){this.K||this.sa||b.target!==this.hb||(this.I=this.Ec=!0,this.pa=-1,W(this),Db(this.s,"ended",this.fa,this.Jb))}U(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Ec}fc(){return!this.o||this.I?!0:this.U()}Ia(){let b;b=this.K?this.P:this.Wb+(V(this)-this.Yb)*this.la;this.X||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Mc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ia;this.o.connect(this.G);this.hb=this.o;this.o.onended=this.Vb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Ec=!1;this.X=b;this.la=1;this.Yb=V(this);this.Wb=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.pa=-1}fb(){this.K||this.I||this.U()||(this.P=this.Ia(),this.X&&(this.P%=this.ga()),this.K=!0,this.o.stop(0))}Eb(){!this.K||this.I||this.U()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ia,this.o.connect(this.G),this.hb=this.o,this.o.onended=this.Vb,this.o.loop=this.X,U(this,this.Ha),this.Ca(),this.o.start(0,this.P),this.Yb=V(this),this.Wb=this.P,this.K=!1)}kc(){return super.kc()*this.Mc}Ib(){this.Mc=this.Pa||this.Cb()?0:1;U(this,this.Ha)}oc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Ca(){let b=this.la;this.Jc&&(b*=this.s.bc);this.o&&(this.o.playbackRate.value=b)}nc(b){this.I||this.U()||(this.K?this.P=b:(this.fb(),this.P=
b,this.Eb()))}lc(){return this.P}pc(b){b?this.IsPlaying()?(this.sa=!0,this.P=this.Ia(),this.X&&(this.P%=this.ga()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ia,this.o.connect(this.G),this.hb=this.o,this.o.onended=this.Vb,this.o.loop=this.X,U(this,this.Ha),this.Ca(),this.o.start(0,this.P),this.Yb=V(this),this.Wb=this.P,this.sa=!1)}uc(b){super.uc(b);this.P=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.V();this.xd=-1;this.R=this.fa="";this.m=null}j(){this.g=null}N(){}S(){}bb(){return{type:this.R,tag:this.fa,params:this.m}}}
self.Sd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.Qd=class extends Z{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.sb=X(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.lb=X(this);this.lb.gain.value=c;this.u.connect(this.sb);this.u.connect(this.h);this.sb.connect(this.i);this.sb.connect(this.W);this.W.connect(this.lb);this.lb.connect(this.sb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.sb.disconnect();
this.W.disconnect();this.lb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){const e=self.$a.Yc;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.lb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.W.delayTime,a,c,d)}}};
self.Pd=class extends Z{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.md=this.ld="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.kb=this.g.createConvolver();this.kb.normalize=c;this.kb.buffer=a;this.u.connect(this.kb);this.u.connect(this.h);this.kb.connect(this.i)}j(){this.u.disconnect();this.kb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}bb(){const b=super.bb();b.bufferOriginalUrl=this.ld;b.bufferUrl="";b.bufferType=this.md;return b}};
self.Td=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.mb=X(this);this.mb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.u.connect(this.W);this.u.connect(this.h);this.W.connect(this.i);this.W.connect(this.mb);this.mb.connect(this.W);this.A.connect(this.L);
this.L.connect(this.W.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.W.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.mb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.mb.gain,a/100,c,d)}}};
self.Vd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.A.connect(this.L);this.L.connect(this.D.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.D.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.A.frequency,a,c,d)}}};self.Ud=class extends Z{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.$a.Yc;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.Xd=class extends Z{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.xb=X(this);this.xb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.xb.gain);this.A.start(0);this.u.connect(this.xb);this.u.connect(this.h);this.xb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.xb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Rd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.u=X(this);this.$b=X(this);this.Zb=X(this);b=d;.01>b&&(b=.01);this.$b.gain.value=b;this.Zb.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.cc=this.g.createWaveShaper();this.Ac=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ac[32768+e]=f,this.Ac[32768-
e-1]=-f;this.cc.curve=this.Ac;this.u.connect(this.$b);this.u.connect(this.h);this.$b.connect(this.cc);this.cc.connect(this.Zb);this.Zb.connect(this.i)}j(){this.u.disconnect();this.$b.disconnect();this.cc.disconnect();this.Zb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Od=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Nd=class extends Z{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.td=new Float32Array(this.l.frequencyBinCount);this.Id=new Uint8Array(a);this.Gd=this.Ua=0;b=this.s;b.Ma.add(this);T(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ka(){this.l.getFloatFrequencyData(this.td);this.l.getByteTimeDomainData(this.Id);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Id[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.$a.ie;this.Ua=c(this.Ua);this.Gd=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};"use strict";
self.gb.Ab(class extends self.ab{constructor(b){super(b,"mouse");t(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.H.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Jb(b,a){a=a.type;let c=!0;0===a?c=await Kb():1===a&&(c=await Lb());k(b,"permission-result",{type:a,result:c})}async function Kb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Lb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.gb.Ab(class extends self.ab{constructor(b){super(b,"touch");p(this,"request-permission",a=>Jb(this,a))}});
